services:
  app:
    container_name: quyle91_github_io_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_network"
      - "traefik.http.routers.quyle91-cv.entrypoints=web"
      - "traefik.http.routers.quyle91-cv.rule=Host(`cv.quyle91.localhost`)"
      - "traefik.http.routers.quyle91-cv.service=quyle91-cv"
      - "traefik.http.services.quyle91-cv.loadbalancer.server.port=3000"

networks:
  proxy_network:
    external: true
